# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_dmvn <- function(x, Sigma) {
    .Call('_mpsBART_log_dmvn', PACKAGE = 'mpsBART', x, Sigma)
}

bspline <- function(x, x_obs) {
    .Call('_mpsBART_bspline', PACKAGE = 'mpsBART', x, x_obs)
}

matrix_tests <- function(matrix, vector) {
    .Call('_mpsBART_matrix_tests', PACKAGE = 'mpsBART', matrix, vector)
}

sbart <- function(x_train, y_train, x_test, B_train, B_test, n_tree, n_mcmc, n_burn, tau, mu, tau_mu, tau_b, tau_b_intercept, alpha, beta, a_tau, d_tau, nu, delta, a_delta, d_delta, a_tau_b, d_tau_b, p_sample, p_sample_levels) {
    .Call('_mpsBART_sbart', PACKAGE = 'mpsBART', x_train, y_train, x_test, B_train, B_test, n_tree, n_mcmc, n_burn, tau, mu, tau_mu, tau_b, tau_b_intercept, alpha, beta, a_tau, d_tau, nu, delta, a_delta, d_delta, a_tau_b, d_tau_b, p_sample, p_sample_levels)
}

mat_init <- function(n) {
    .Call('_mpsBART_mat_init', PACKAGE = 'mpsBART', n)
}

vec_init <- function(n) {
    .Call('_mpsBART_vec_init', PACKAGE = 'mpsBART', n)
}

std_inv <- function(A, diag) {
    .Call('_mpsBART_std_inv', PACKAGE = 'mpsBART', A, diag)
}

std_pinv <- function(A, diag) {
    .Call('_mpsBART_std_pinv', PACKAGE = 'mpsBART', A, diag)
}

faster_simple_std_inv <- function(A, diag) {
    .Call('_mpsBART_faster_simple_std_inv', PACKAGE = 'mpsBART', A, diag)
}

faster_std_inv <- function(A, diag) {
    .Call('_mpsBART_faster_std_inv', PACKAGE = 'mpsBART', A, diag)
}

GPT <- function(B, D) {
    .Call('_mpsBART_GPT', PACKAGE = 'mpsBART', B, D)
}

rMVN2 <- function(b, Q) {
    .Call('_mpsBART_rMVN2', PACKAGE = 'mpsBART', b, Q)
}

rMVNslow <- function(b, Q) {
    .Call('_mpsBART_rMVNslow', PACKAGE = 'mpsBART', b, Q)
}

rand_unif <- function() {
    .Call('_mpsBART_rand_unif', PACKAGE = 'mpsBART')
}

